### ISSUE TITLE
Add OAuth Client Support for iPaaS Console

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-ipaas#49]
We'll need to implement some oauth flow soon for the ipaas console to work against openshift using an oauth provider.

## Reference
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-33)

**Comment by gashcrumb** [comment]
@kahboom FYI this commit changes the dev mode port from 1337 to 9000, beats having to update the openshift config

@alexkieling [FYI](https://github.com/hawtio/hawtio-ipaas/blob/master/src/app/oauth.service.ts)

Outstanding item is figuring out why my authorization header isn't being used when invoking on the kubernetes API.

**Comment by kahboom** [comment]
@gashcrumb - Can this be moved to 'Testing' in the [Projects Kanban board](https://github.com/hawtio/hawtio-ipaas/projects/4#card-591673) already, or even 'Complete', or are you still working on it?

**Comment by gashcrumb** [comment]
@kahboom yeah, think this is good to go, moving it...
